//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class indexdefinegroup : EntityBase
    {
        public indexdefinegroup()
        {
            this.indexdefinition = new HashSet<indexdefinition>();
        }
    
        public string code { get; set; }
        public string group_name { get; set; }
    
        public virtual ICollection<indexdefinition> indexdefinition { get; set; }
    }
}
