//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class indexdefinition : EntityBase
    {
        public indexdefinition()
        {
            this.index_user_map = new HashSet<index_user_map>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string parameter { get; set; }
        public string fields { get; set; }
        public string table_name { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> version { get; set; }
        public string group_code { get; set; }
        public string algorithm_script { get; set; }
        public string chart_config { get; set; }
    
        public virtual indexdefinegroup indexdefinegroup { get; set; }
        public virtual ICollection<index_user_map> index_user_map { get; set; }
    }
}
