//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class objectstate_history : EntityBase
    {
        public string code { get; set; }
        public string object_code { get; set; }
        public string index_code { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string category_code { get; set; }
    }
}
