//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class reco_category_count : EntityBase
    {
        public string code { get; set; }
        public string cate_code { get; set; }
        public string cate_type { get; set; }
        public string index_code { get; set; }
        public Nullable<int> count { get; set; }
    }
}
