//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class related_object_define : EntityBase
    {
        public related_object_define()
        {
            this.related_object_fields = new HashSet<related_object_fields>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<double> last_value { get; set; }
    
        public virtual ICollection<related_object_fields> related_object_fields { get; set; }
    }
}
