//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class related_object_data : EntityBase
    {
        public string code { get; set; }
        public string type { get; set; }
        public Nullable<double> pro0 { get; set; }
        public Nullable<double> pro1 { get; set; }
        public Nullable<double> pro2 { get; set; }
        public Nullable<double> pro3 { get; set; }
        public Nullable<double> pro4 { get; set; }
        public Nullable<double> pro5 { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
