//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule : EntityBase
    {
        public rule()
        {
            this.rulecondition = new HashSet<rulecondition>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string user_id { get; set; }
        public Nullable<int> state { get; set; }
        public string description { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<rulecondition> rulecondition { get; set; }
    }
}
