//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_comments : EntityBase
    {
        public int code { get; set; }
        public Nullable<int> parent_code { get; set; }
        public Nullable<int> index { get; set; }
        public string object_code { get; set; }
        public string content { get; set; }
        public Nullable<int> up { get; set; }
        public Nullable<int> down { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
