//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_message : EntityBase
    {
        public string code { get; set; }
        public string user_id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string hint { get; set; }
        public string title { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> notice_state { get; set; }
    }
}
