//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_position : EntityBase
    {
        public string code { get; set; }
        public string user_id { get; set; }
        public Nullable<int> position { get; set; }
        public string stock_code { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
