//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdataversion : EntityBase
    {
        public string code { get; set; }
        public Nullable<decimal> version { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string user_id { get; set; }
    }
}
