//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users : EntityBase
    {
        public users()
        {
            this.stock_user_map = new HashSet<stock_user_map>();
            this.rule = new HashSet<rule>();
            this.index_user_map = new HashSet<index_user_map>();
            this.object_user_map = new HashSet<object_user_map>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public Nullable<decimal> exp { get; set; }
        public Nullable<decimal> points { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string sso { get; set; }
    
        public virtual ICollection<stock_user_map> stock_user_map { get; set; }
        public virtual ICollection<rule> rule { get; set; }
        public virtual ICollection<index_user_map> index_user_map { get; set; }
        public virtual ICollection<object_user_map> object_user_map { get; set; }
    }
}
