//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.Message.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mq_message
    {
        public string code { get; set; }
        public string task_code { get; set; }
        public Nullable<int> status { get; set; }
        public string values { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
