//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.Message.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mq_message
    {
        public string code { get; set; }
        public string task_code { get; set; }
        public Nullable<int> status { get; set; }
        public string values { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
