//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.Web.RestService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockManDBEntities : DbContext
    {
        public StockManDBEntities()
            : base("name=StockManDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Stock> Stock { get; set; }
        public DbSet<StockCategory> StockCategory { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Stock_User_Map> Stock_User_Map { get; set; }
        public DbSet<Stock_Category_Group> Stock_Category_Group { get; set; }
        public DbSet<Stock_Category_Map> Stock_Category_Map { get; set; }
    }
}
