//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.Web.RestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Category_Map
    {
        public string category_code { get; set; }
        public string stock_code { get; set; }
    }
}
