//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.Web.RestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Stock_User_Map = new HashSet<Stock_User_Map>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public Nullable<decimal> exp { get; set; }
        public Nullable<decimal> points { get; set; }
    
        public virtual ICollection<Stock_User_Map> Stock_User_Map { get; set; }
    }
}
