//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class indexdefinition : EntityBase
    {
        public indexdefinition()
        {
            this.index_user_map = new HashSet<index_user_map>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string parameter { get; set; }
        public string fields { get; set; }
        public string table_name { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> version { get; set; }
        public string group_code { get; set; }
        public string algorithm_script { get; set; }
        public string chart_config { get; set; }
    
        public virtual indexdefinegroup indexdefinegroup { get; set; }
        public virtual ICollection<index_user_map> index_user_map { get; set; }
    }
}
