//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricesynclog : EntityBase
    {
        public int id { get; set; }
        public string batch { get; set; }
        public string stock_code { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> creatime { get; set; }
        public Nullable<int> state { get; set; }
    }
}
