//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class related_object_data : EntityBase
    {
        public string code { get; set; }
        public string type { get; set; }
        public Nullable<double> pro0 { get; set; }
        public Nullable<double> pro1 { get; set; }
        public Nullable<double> pro2 { get; set; }
        public Nullable<double> pro3 { get; set; }
        public Nullable<double> pro4 { get; set; }
        public Nullable<double> pro5 { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
