//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock : EntityBase
    {
        public stock()
        {
            this.stock_category_map = new HashSet<stock_category_map>();
            this.stock_user_map = new HashSet<stock_user_map>();
        }
    
        public string code { get; set; }
        public string symbol { get; set; }
        public string spell { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> yestclose { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<decimal> turnover { get; set; }
        public Nullable<decimal> high { get; set; }
        public Nullable<decimal> updown { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> turnoverrate { get; set; }
        public Nullable<decimal> pe { get; set; }
        public Nullable<decimal> pb { get; set; }
        public Nullable<decimal> fv { get; set; }
        public Nullable<decimal> mv { get; set; }
        public Nullable<decimal> percent { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> open { get; set; }
    
        public virtual ICollection<stock_category_map> stock_category_map { get; set; }
        public virtual ICollection<stock_user_map> stock_user_map { get; set; }
    }
}
