//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.MySqlAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using StockMan.EntityModel;
    
    public partial class StockManDBEntities : DbContext
    {
        public StockManDBEntities()
            : base("name=StockManDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customobject> customobject { get; set; }
        public DbSet<customobject_category_map> customobject_category_map { get; set; }
        public DbSet<customobject_user_map> customobject_user_map { get; set; }
        public DbSet<data_category_day_latest> data_category_day_latest { get; set; }
        public DbSet<data_category_month_latest> data_category_month_latest { get; set; }
        public DbSet<data_category_week_latest> data_category_week_latest { get; set; }
        public DbSet<data_object_day_latest> data_object_day_latest { get; set; }
        public DbSet<data_object_month_latest> data_object_month_latest { get; set; }
        public DbSet<data_object_week_latest> data_object_week_latest { get; set; }
        public DbSet<data_stock_day_latest> data_stock_day_latest { get; set; }
        public DbSet<data_stock_month_latest> data_stock_month_latest { get; set; }
        public DbSet<data_stock_week_latest> data_stock_week_latest { get; set; }
        public DbSet<index_user_map> index_user_map { get; set; }
        public DbSet<indexdefinegroup> indexdefinegroup { get; set; }
        public DbSet<indexdefinition> indexdefinition { get; set; }
        public DbSet<object_user_map> object_user_map { get; set; }
        public DbSet<objectcategory> objectcategory { get; set; }
        public DbSet<objectstate> objectstate { get; set; }
        public DbSet<objectstate_history> objectstate_history { get; set; }
        public DbSet<pricesynclog> pricesynclog { get; set; }
        public DbSet<rule> rule { get; set; }
        public DbSet<stock> stock { get; set; }
        public DbSet<stock_category_group> stock_category_group { get; set; }
        public DbSet<stock_category_map> stock_category_map { get; set; }
        public DbSet<stock_new> stock_new { get; set; }
        public DbSet<stock_user_map> stock_user_map { get; set; }
        public DbSet<stockcategory> stockcategory { get; set; }
        public DbSet<stockcategory_user_map> stockcategory_user_map { get; set; }
        public DbSet<sys_goodidea> sys_goodidea { get; set; }
        public DbSet<sys_investdata> sys_investdata { get; set; }
        public DbSet<sys_userconfig> sys_userconfig { get; set; }
        public DbSet<user_investintention> user_investintention { get; set; }
        public DbSet<userdataversion> userdataversion { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<rulecondition> rulecondition { get; set; }
        public DbSet<reco_stock_category_index> reco_stock_category_index { get; set; }
        public DbSet<user_message> user_message { get; set; }
        public DbSet<related_object_define> related_object_define { get; set; }
        public DbSet<related_object_fields> related_object_fields { get; set; }
        public DbSet<tech_context> tech_context { get; set; }
        public DbSet<reco_user_stock> reco_user_stock { get; set; }
        public DbSet<related_object_data> related_object_data { get; set; }
        public DbSet<reco_category_count> reco_category_count { get; set; }
        public DbSet<reco_stock_category_rank> reco_stock_category_rank { get; set; }
        public DbSet<object_tag_map> object_tag_map { get; set; }
        public DbSet<tag> tag { get; set; }
        public DbSet<reco_stock_category_tag> reco_stock_category_tag { get; set; }
        public DbSet<reco_stock_category_state> reco_stock_category_state { get; set; }
        public DbSet<user_amount> user_amount { get; set; }
        public DbSet<user_trade> user_trade { get; set; }
        public DbSet<user_position> user_position { get; set; }
        public DbSet<user_strategy> user_strategy { get; set; }
    }
}
