//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_goodidea : EntityBase
    {
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> up { get; set; }
        public Nullable<int> down { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> state { get; set; }
        public string createuser { get; set; }
    }
}
