//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_investintention : EntityBase
    {
        public string code { get; set; }
        public string user_id { get; set; }
        public string trade { get; set; }
        public string tech { get; set; }
        public string market { get; set; }
        public string investamount { get; set; }
        public string job { get; set; }
        public string investmethod { get; set; }
        public string learnmethod { get; set; }
        public string apps { get; set; }
        public string infosource { get; set; }
        public string book { get; set; }
        public string econ { get; set; }
    }
}
