//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_investintention : EntityBase
    {
        public string code { get; set; }
        public string user_id { get; set; }
        public string trade { get; set; }
        public string tech { get; set; }
        public string market { get; set; }
        public string investamount { get; set; }
        public string job { get; set; }
        public string investmethod { get; set; }
        public string learnmethod { get; set; }
        public string apps { get; set; }
        public string infosource { get; set; }
        public string book { get; set; }
        public string econ { get; set; }
    }
}
