//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMan.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users : EntityBase
    {
        public users()
        {
            this.stock_user_map = new HashSet<stock_user_map>();
            this.rule = new HashSet<rule>();
            this.index_user_map = new HashSet<index_user_map>();
            this.object_user_map = new HashSet<object_user_map>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public Nullable<decimal> exp { get; set; }
        public Nullable<decimal> points { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string sso { get; set; }
    
        public virtual ICollection<stock_user_map> stock_user_map { get; set; }
        public virtual ICollection<rule> rule { get; set; }
        public virtual ICollection<index_user_map> index_user_map { get; set; }
        public virtual ICollection<object_user_map> object_user_map { get; set; }
    }
}
